## Упражнения по библиотеке Numpy

In [2]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [3]:
arr = np.random.randint(0, 10, size=10)
print("Original array: ", arr)

mask = (arr >= 3) & (arr <= 8)
arr[mask] *= -1
print("Modified array: ", arr)

Original array:  [7 4 3 3 7 5 1 0 8 1]
Modified array:  [-7 -4 -3 -3 -7 -5  1  0 -8  1]


**2.** Заменить максимальный элемент случайного массива на 0

In [4]:
arr = np.random.randint(0, 10, size=10)
print("Original array: ", arr)

arr[arr.argmax()] = 0
print("Modified array: ", arr)

Original array:  [4 1 7 6 8 7 9 2 2 0]
Modified array:  [4 1 7 6 8 7 0 2 2 0]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [5]:
from itertools import product
arr = np.array([[1, 2], [3, 4]])
combinations = np.array(list(product(*arr.T)))
print(combinations)

[[1 2]
 [1 4]
 [3 2]
 [3 4]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [4]:
A = np.random.randint(0, 10, (8, 3))
B = np.random.randint(0, 10, (2, 2))
print(A)
print(B)
C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[[7 8 9]
 [6 9 2]
 [9 9 7]
 [7 4 0]
 [8 2 9]
 [9 6 4]
 [5 9 5]
 [4 3 8]]
[[7 2]
 [7 9]]
[0 1 2 3 4]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [3]:
A = np.random.randint(0,2,(10,3))
print(A)
B = np.logical_and.reduce(A[:, :-1] == A[:, 1:],axis=1)
C  = A[~B]
print(C)

[[0 1 1]
 [0 1 0]
 [0 1 1]
 [1 1 1]
 [0 0 0]
 [1 1 1]
 [0 1 1]
 [1 1 0]
 [1 1 0]
 [0 0 0]]
[[0 1 1]
 [0 1 0]
 [0 1 1]
 [0 1 1]
 [1 1 0]
 [1 1 0]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [6]:
arr = np.random.randint(0, 3, (4, 3))
print(arr)
unique = np.unique(arr, axis=0)
print(unique)

[[2 1 2]
 [0 2 2]
 [2 1 1]
 [0 2 2]]
[[0 2 2]
 [2 1 1]
 [2 1 2]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [7]:
import time
X = np.array([[1, 0, 1],
              [2, 0, 2],
              [3, 0, 3],
              [4, 4, 4]])

def diag_product_without_numpy(m):
  product = 1
  for i in range(min(len(m), len(m[0]))):
    el = m[i][i]
    if el != 0:
      product *= el
  return product

def diag_product_with_numpy(m):
  diag = np.diagonal(m)
  return np.prod(diag[diag != 0])

start = time.time()
res1 = diag_product_without_numpy(X)
end = time.time()
print(f"Without NumPy: {res1}, time: {end - start:.6f} s")

start = time.time()
res2 = diag_product_with_numpy(X)
end = time.time()
print(f"With NumPy: {res2}, time: {end - start:.6f} s")

Without NumPy: 3, time: 0.000110 s
With NumPy: 3, time: 0.000224 s


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [8]:
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])

def multiset_without_numpy(x, y):
  return sorted(x) == sorted(y)

def multiset_with_numpy(x, y):
  return np.array_equal(np.sort(x), np.sort(y))

start = time.time()
res1 = multiset_without_numpy(x, y)
end = time.time()
print(f"Without NumPy: {res1}, time: {end - start:.6f} s")

start = time.time()
res2 = multiset_with_numpy(x, y)
end = time.time()
print(f"With NumPy: {res2}, time: {end - start:.6f} s")

Without NumPy: True, time: 0.000070 s
With NumPy: True, time: 0.005280 s


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль.
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [9]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

def max_after_zero_without_numpy(x):
  result = [x[i] for i in range(1, len(x)) if x[i-1] == 0]
  return max(result)

def max_after_zero_with_numpy(x):
  return np.max(x[1:][x[:-1] == 0])

start = time.time()
res1 = max_after_zero_without_numpy(x)
end = time.time()
print(f"Without NumPy: {res1}, time: {end - start:.6f} s")

start = time.time()
res2 = max_after_zero_with_numpy(x)
end = time.time()
print(f"With NumPy: {res2}, time: {end - start:.6f} s")

Without NumPy: 5, time: 0.000067 s
With NumPy: 5, time: 0.000127 s


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [11]:
x = np.array([2, 2, 2, 3, 3, 3, 5])

def length_encoding_without_numpy(x):
  values = []
  counts = []

  prev = x[0]
  count = 1

  for i in range(1, len(x)):
    if x[i] == prev:
      count += 1
    else:
      values.append(prev)
      counts.append(count)
      prev = x[i]
      count = 1

  values.append(prev)
  counts.append(count)

  return values, counts

def length_encoding_with_numpy(x):
  points = np.flatnonzero(np.diff(x) != 0) + 1
  results = np.concatenate(([0], points, [len(x)]))

  values = x[results[:-1]]
  counts = np.diff((results))

  return values, counts

start = time.time()
res1 = length_encoding_without_numpy(x)
end = time.time()
print(f"Without NumPy: {res1}, time: {end - start:.6f} s")

start = time.time()
res2 = length_encoding_with_numpy(x)
end = time.time()
print(f"With NumPy: {res2}, time: {end - start:.6f} s")

Without NumPy: ([np.int64(2), np.int64(3), np.int64(5)], [3, 3, 1]), time: 0.000089 s
With NumPy: (array([2, 3, 5]), array([3, 3, 1])), time: 0.000256 s


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [13]:
import time
from scipy.spatial.distance import cdist

m, n, d = 1000, 800, 50
X = np.random.rand(m, d)
Y = np.random.rand(n, d)

def euclidian_distances_without_numpy(X, Y):
  result = []
  for x in X:
    row = []
    for y in Y:
      distance = 0
      for xi, yi in zip(x, y):
        distance += (xi - yi)**2
      row.append(distance**0.5)
    result.append(row)
  return result

def euclidian_distances_with_numpy(X, Y):
  return cdist(X, Y, metric='euclidean')

start = time.time()
res1 = euclidian_distances_without_numpy(X, Y)
end = time.time()
print(f"Without NumPy: time: {end - start:.6f} s")

start = time.time()
res2 = euclidian_distances_with_numpy(X, Y)
end = time.time()
print(f"With NumPy: time: {end - start:.6f} s")

Without NumPy: time: 12.782361 s
With NumPy: time: 0.091815 s


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [3]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [7]:
calorie_stats = np.loadtxt("cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [8]:
crunchies_calories = 60
average_calories = np.mean(calorie_stats) - crunchies_calories
print("{:.2f}".format(average_calories))

46.88


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [9]:
calorie_stats_sorted = np.sort(calorie_stats)
print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [10]:
median_calories = np.median(calorie_stats)
mean_calories = np.mean(calorie_stats)
print(f"Average calories: {mean_calories}")
print(f"Median calories: {median_calories}")
#The calorie distribution is slightly left-skewed

Average calories: 106.88311688311688
Median calories: 110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [11]:
percentiles = np.percentile(calorie_stats, np.arange(101))
percentiles
nth_percentile = None
for i, val in enumerate(percentiles):
    if val > 60:
        nth_percentile = i
        print(f"The smallest percentile with calories > 60 is the {i}th percentile, value: {val}.")
        break

The smallest percentile with calories > 60 is the 4th percentile, value: 70.0.


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [12]:
more_calories = np.sum(calorie_stats > 60) / len(calorie_stats) * 100
print(f"Percentage of cereals with calories greater than 60: {more_calories:.2f}%")

Percentage of cereals with calories greater than 60: 96.10%


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [ ]:
calorie_std = np.std(calorie_stats)
print(f"Calorie standard deviation: {calorie_std:.2f}")

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [ ]:
# your code